# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-05-08 18:03
from __future__ import unicode_literals

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('day', models.DateField(default=datetime.datetime.now)),
                ('time_slot', models.CharField(choices=[('morning_first', '12h00'), ('morning_second', '13h00'), ('morning_third', '14h00'), ('morning_fourth', '15h00'), ('evening_first', '20h00'), ('evening_second', '21h00'), ('evening_third', '22h00')], max_length=15)),
                ('num_people', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_number', models.CharField(max_length=8, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('menu_description', models.TextField()),
                ('price_average', models.DecimalField(decimal_places=2, max_digits=5)),
                ('is_promot', models.BooleanField()),
                ('rate', models.DecimalField(decimal_places=1, max_digits=3)),
                ('address', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('featured_photo', models.ImageField(upload_to='restaurant_imgs')),
                ('category', models.CharField(choices=[('Rice', 'Rice'), ('Fusi', 'Fusion'), ('BBQ', 'Barbecue'), ('Chin', 'Chinese'), ('Medi', 'Mediterranean'), ('Crep', 'Creperie'), ('Hind', 'Hindu'), ('Japa', 'Japanese'), ('Ital', 'Italian'), ('Mexi', 'Mexican'), ('Peru', 'Peruvian'), ('Russ', 'Russian'), ('Turk', 'Turkish'), ('Basq', 'Basque'), ('Vegy', 'Vegetarian'), ('Afri', 'African'), ('Egyp', 'Egyptian'), ('Grek', 'Greek')], max_length=5)),
                ('capacity', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('review_message', models.CharField(max_length=500)),
                ('stars', models.IntegerField()),
                ('user', models.CharField(default='Anonymous', max_length=100)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forkilla.Restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='ViewedRestaurants',
            fields=[
                ('id_vr', models.AutoField(primary_key=True, serialize=False)),
                ('restaurant', models.ManyToManyField(to='forkilla.Restaurant')),
            ],
        ),
        migrations.AddField(
            model_name='reservation',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forkilla.Restaurant'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
